const groups = [{
    name: "Mixed Young Adult Small Group",
    leader: "Jordan Grogan",
    neighborhood: "Moon",
    lat: 40.508670,
    long: -80.216240,
    filters: {
        typeMens: false,
        typeWomens: false,
        typeMixed: true,
        age20s: true,
        age30s: false,
        age40s: false,
        age50s: false,
        age60splus: false,
        daySun: false,
        dayMon: false,
        dayTues: false,
        dayWed: false,
        dayThurs: true,
        dayFri: false,
        daySat: false,
        timeMorning: false,
        timeAfternoon: false,
        timeEvening: true,
        childcare: false,
        noChildcare: true
    }
}, {
    name: "Another Small Group",
    leader: "Jordan Grogan",
    neighborhood: "Moon",
    lat: 40.4286730,
    long: -80.216240,
    filters: {
        typeMens: false,
        typeWomens: false,
        typeMixed: true,
        age20s: true,
        age30s: true,
        age40s: false,
        age50s: false,
        age60splus: false,
        daySun: false,
        dayMon: false,
        dayTues: false,
        dayWed: false,
        dayThurs: true,
        dayFri: false,
        daySat: false,
        timeMorning: false,
        timeAfternoon: false,
        timeEvening: true,
        childcare: false,
        noChildcare: true
    }
}];